Repository URECA-Dapanda/dapanda-backend, pull requests merged in 2025-07, with the labels that each got.

#4 [DP-11] feat: Entity 초기 세팅
  .gitignore
  build.gradle
  src/main/java/com/dapanda/Application.java
  src/main/java/com/dapanda/common/entity/BaseEntity.java
  src/main/java/com/dapanda/common/entity/CreatedAtEntity.java
  src/main/java/com/dapanda/common/entity/UpdatedAtEntity.java
  src/main/java/com/dapanda/common/exception/BaseException.java
  src/main/java/com/dapanda/common/exception/CommonResponse.java
  src/main/java/com/dapanda/common/exception/GlobalException.java
  src/main/java/com/dapanda/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dapanda/event/entity/AttendanceCheck.java
  src/main/java/com/dapanda/event/entity/MemberPanda.java
  src/main/java/com/dapanda/event/entity/Panda.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/entity/MemberRole.java
  src/main/java/com/dapanda/plan/entity/AgeGroup.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/plan/entity/PlanCategory.java
  src/main/java/com/dapanda/product/entity/DataSellingUnit.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/entity/Product.java
  src/main/java/com/dapanda/product/entity/ProductState.java
  src/main/java/com/dapanda/product/entity/ProductType.java
  src/main/java/com/dapanda/product/entity/Wifi.java
  src/main/java/com/dapanda/product/entity/WifiSellingUnit.java
  src/main/java/com/dapanda/refreshToken/entity/RefreshToken.java
  src/main/java/com/dapanda/refreshToken/entity/TokenState.java
  src/main/java/com/dapanda/report/entity/Report.java
  src/main/java/com/dapanda/report/entity/ReportTargetCategory.java
  src/main/java/com/dapanda/report/entity/ReportType.java
  src/main/java/com/dapanda/review/entity/Review.java
  src/main/java/com/dapanda/tradeHistory/entity/TradeHistory.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/dapanda/ApplicationTests.java
  src/test/java/com/dapanda/TestApplication.java
  src/test/java/com/dapanda/TestcontainersConfiguration.java
Labels: BE, feat

#24 [DP-31] chore: PR 템플릿 수정 #23
  .github/PULL_REQUEST_TEMPLATE.md
Labels: BE, chore

#28 [DP-27] feat: 소셜 로그인 기능
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/dapanda/Application.java
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/auth/dto/request/LoginRequest.java
  src/main/java/com/dapanda/auth/dto/request/SignupRequest.java
  src/main/java/com/dapanda/auth/dto/response/LoginResponse.java
  src/main/java/com/dapanda/auth/dto/response/SignupResponse.java
  src/main/java/com/dapanda/auth/dto/response/TokenResponse.java
  src/main/java/com/dapanda/auth/entity/CustomUserDetails.java
  src/main/java/com/dapanda/auth/entity/OAuthProvider.java
  src/main/java/com/dapanda/auth/handler/OAuth2FailureHandler.java
  src/main/java/com/dapanda/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/dapanda/auth/info/GoogleOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/KakaoOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/NaverOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/OAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/OAuth2UserInfoFactory.java
  src/main/java/com/dapanda/auth/service/AuthService.java
  src/main/java/com/dapanda/auth/service/CustomOAuth2UserService.java
  src/main/java/com/dapanda/auth/service/CustomUserDetailsService.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/event/entity/AttendanceCheck.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/jwt/JwtProperties.java
  src/main/java/com/dapanda/jwt/JwtTokenProvider.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/repository/MemberRepository.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/refreshToken/entity/RefreshToken.java
  src/main/java/com/dapanda/refreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/dapanda/refreshToken/service/RefreshTokenService.java
  src/test/java/com/dapanda/RestDocsConfig.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/auth/service/AuthServiceTest.java
  src/test/java/com/dapanda/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: BE, feat

#29 [DP-33] feat: 리뷰 등록 기능 추가
  .gitignore
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/Application.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/common/entity/BaseEntity.java
  src/main/java/com/dapanda/common/entity/CreatedAtEntity.java
  src/main/java/com/dapanda/common/entity/UpdatedAtEntity.java
  src/main/java/com/dapanda/common/exception/CommonResponse.java
  src/main/java/com/dapanda/common/exception/GlobalException.java
  src/main/java/com/dapanda/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/event/entity/AttendanceCheck.java
  src/main/java/com/dapanda/event/entity/MemberPanda.java
  src/main/java/com/dapanda/event/entity/Panda.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/jwt/JwtProperties.java
  src/main/java/com/dapanda/jwt/JwtTokenProvider.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/entity/MemberRole.java
  src/main/java/com/dapanda/member/repository/MemberRepository.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/plan/entity/AgeGroup.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/plan/entity/PlanCategory.java
  src/main/java/com/dapanda/product/entity/DataSellingUnit.java
  src/main/java/com/dapanda/product/entity/ItemType.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/entity/Product.java
  src/main/java/com/dapanda/product/entity/ProductState.java
  src/main/java/com/dapanda/product/entity/ProductType.java
  src/main/java/com/dapanda/product/entity/Wifi.java
  src/main/java/com/dapanda/product/entity/WifiSellingUnit.java
  src/main/java/com/dapanda/refreshToken/entity/RefreshToken.java
  src/main/java/com/dapanda/refreshToken/entity/TokenState.java
  src/main/java/com/dapanda/refreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/dapanda/refreshToken/service/RefreshTokenService.java
  src/main/java/com/dapanda/report/entity/Report.java
  src/main/java/com/dapanda/report/entity/ReportTargetCategory.java
  src/main/java/com/dapanda/report/entity/ReportType.java
  src/main/java/com/dapanda/review/controller/ReviewController.java
  src/main/java/com/dapanda/review/dto/request/SaveReviewRequest.java
  src/main/java/com/dapanda/review/dto/response/SaveReviewResponse.java
  src/main/java/com/dapanda/review/entity/Review.java
  src/main/java/com/dapanda/review/repository/ReviewRepository.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/main/java/com/dapanda/tradeHistory/entity/TradeHistory.java
  src/test/java/com/dapanda/RestDocsConfig.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/member/service/MemberServiceTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, feat

#33 [DP-37] test: 인증/인가 시스템 테스트 코드 추가 #31
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/auth/dto/request/LoginRequest.java
  src/main/java/com/dapanda/auth/dto/request/SignupRequest.java
  src/main/java/com/dapanda/auth/dto/response/LoginResponse.java
  src/main/java/com/dapanda/auth/dto/response/SignupResponse.java
  src/main/java/com/dapanda/auth/dto/response/TokenResponse.java
  src/main/java/com/dapanda/auth/entity/CustomUserDetails.java
  src/main/java/com/dapanda/auth/entity/OAuthProvider.java
  src/main/java/com/dapanda/auth/handler/OAuth2FailureHandler.java
  src/main/java/com/dapanda/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/dapanda/auth/info/GoogleOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/KakaoOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/NaverOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/OAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/OAuth2UserInfoFactory.java
  src/main/java/com/dapanda/auth/service/AuthService.java
  src/main/java/com/dapanda/auth/service/CustomOAuth2UserService.java
  src/main/java/com/dapanda/auth/service/CustomUserDetailsService.java
  src/main/java/com/dapanda/common/entity/BaseEntity.java
  src/main/java/com/dapanda/common/entity/CreatedAtEntity.java
  src/main/java/com/dapanda/common/entity/UpdatedAtEntity.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/event/entity/AttendanceCheck.java
  src/main/java/com/dapanda/event/entity/MemberPanda.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/product/entity/ProductType.java
  src/main/java/com/dapanda/product/entity/Wifi.java
  src/main/java/com/dapanda/report/entity/Report.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/auth/service/AuthServiceTest.java
  src/test/java/com/dapanda/member/service/MemberServiceTest.java
Labels: BE, test

#35 [DP-34] feat: 캐시 충전 기능 #27
  build.gradle
  gradlew
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/config/WebClientConfig.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/payment/controller/PaymentController.java
  src/main/java/com/dapanda/payment/dto/ConfirmPaymentResponse.java
  src/main/java/com/dapanda/payment/dto/request/AmountRequest.java
  src/main/java/com/dapanda/payment/dto/request/TossConfirmRequest.java
  src/main/java/com/dapanda/payment/dto/response/TossConfirmResponse.java
  src/main/java/com/dapanda/payment/entity/Payment.java
  src/main/java/com/dapanda/payment/repository/PaymentRepository.java
  src/main/java/com/dapanda/payment/service/PaymentService.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/resources/application.yml
  src/test/java/com/dapanda/payment/controller/PaymentControllerTest.java
  src/test/java/com/dapanda/payment/service/PaymentServiceTest.java
  src/test/resources/application-test.yml
Labels: feat

#39 [DP-42] feat: 리뷰 삭제 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/review/controller/ReviewController.java
  src/main/java/com/dapanda/review/dto/request/DeleteReviewRequest.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/test/java/com/dapanda/TestConfig.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/payment/controller/PaymentControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/entity/ReviewFixture.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, feat

#43 [DP-53] feat: 리뷰 수정 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/review/controller/ReviewController.java
  src/main/java/com/dapanda/review/dto/request/UpdateReviewRequest.java
  src/main/java/com/dapanda/review/dto/response/UpdateReviewResponse.java
  src/main/java/com/dapanda/review/entity/Review.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/entity/ReviewFixture.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, feat

#37 [DP-43] feat: CD 구성
  .github/workflows/cd.yml
  appspec.yml
  build.gradle
  scripts/install.sh
  scripts/start.sh
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: BE, feat

#48 [DP-51] feat: 상품 상세 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/dto/response/MobileDataInfoResponse.java
  src/main/java/com/dapanda/product/dto/response/WifiInfoResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/product/entity/WifiFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, feat

#54 [DP-69] docs: README.md 작성
  README.md
Labels: BE, docs

#56 [DP-75] refactor: 리뷰 Controller URI 리펙터링
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/review/controller/ReviewController.java
  src/main/java/com/dapanda/review/dto/request/CreateReviewRequest.java
  src/main/java/com/dapanda/review/dto/request/DeleteReviewRequest.java
  src/main/java/com/dapanda/review/dto/request/UpdateReviewRequest.java
  src/main/java/com/dapanda/review/dto/response/CreateReviewResponse.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, docs, refactor

#47 [DP-62] feat: 배포환경에 RestDocs 구성
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/Application.java
  src/main/java/com/dapanda/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/dapanda/common/config/RestDocsWebConfig.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/event/entity/AttendanceCheck.java
  src/main/java/com/dapanda/event/entity/MemberPanda.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/product/entity/Product.java
  src/main/java/com/dapanda/refreshToken/entity/RefreshToken.java
  src/main/resources/application.yml
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
Labels: BE, feat, docs

#62 [DP-81] fix: 인증/인가 기능수정
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
Labels: BE, fix

#59 [DP-19] feat: 신고 등록 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/repository/MemberRepository.java
  src/main/java/com/dapanda/member/repository/MemberRepositoryCustom.java
  src/main/java/com/dapanda/member/repository/MemberRepositoryImpl.java
  src/main/java/com/dapanda/report/controller/ReportController.java
  src/main/java/com/dapanda/report/dto/request/CreateReportRequest.java
  src/main/java/com/dapanda/report/dto/response/CreateReportResponse.java
  src/main/java/com/dapanda/report/entity/Report.java
  src/main/java/com/dapanda/report/entity/ReportTargetCategory.java
  src/main/java/com/dapanda/report/entity/ReportType.java
  src/main/java/com/dapanda/report/repository/ReportRepository.java
  src/main/java/com/dapanda/report/service/ReportService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/report/controller/ReportControllerTest.java
  src/test/java/com/dapanda/report/entity/ReportFixture.java
  src/test/java/com/dapanda/report/service/ReportServiceTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
Labels: BE, feat, docs

#65 [DP-84] fix: 상품 목록 조회시 updatedAt 필드 반환하도록 수정
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/dto/MobileDataSummary.java
  src/main/java/com/dapanda/product/dto/WifiSummary.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/product/entity/WifiFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, fix

#76 [DP-90] fix: 상품 목록 조회시 RequestParam으로 수정
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, fix

#70 [DP-86] feat: 회원가입 시 요금제 자동 추가 기능
  src/main/java/com/dapanda/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/plan/repository/PlanRepository.java
  src/main/java/com/dapanda/plan/service/PlanService.java
  src/test/java/com/dapanda/plan/service/PlanServiceTest.java
Labels: BE, feat, test

#77 [DP-92] feat : AWS ElastiCache 추가
  src/main/resources/application.yml
Labels: BE, feat

#71 [DP-88] feat: 채팅방 관련 Entity, Repository 추가
  src/main/java/com/dapanda/chat/entity/ChatMessage.java
  src/main/java/com/dapanda/chat/entity/ChatParticipant.java
  src/main/java/com/dapanda/chat/entity/ChatRoom.java
  src/main/java/com/dapanda/chat/entity/ChatRoomState.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepository.java
  src/main/java/com/dapanda/chat/repository/ChatParticipantRepository.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepository.java
Labels: BE, feat

#79 [DP-89] feat: 회원 상품 판매 정보 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/dto/request/ReadSellingProductRequest.java
  src/main/java/com/dapanda/product/dto/response/ReadSellingProductResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, feat, docs, test

#83 [DP-76] feat: 데이터 상품 일반 구매 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/payment/service/PaymentService.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/plan/service/PlanService.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/repository/ProductRepository.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/request/TradeMobileDataDefaultRequest.java
  src/main/java/com/dapanda/trade/dto/response/TradeMobileDataDefaultResponse.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/plan/service/entity/PlanFixture.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat

#88 [DP-101] feat: 데이터 분할 상품 일반 구매 기능
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/trade/dto/request/TradeMobileDataDefaultRequest.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, test

#89 [DP-104] feat: 데이터 상품 자투리 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/MobileDataScrap.java
  src/main/java/com/dapanda/trade/dto/response/FindMobileDataScrapResponse.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, docs, test

#90 [DP-87] feat: 채팅방 생성 기능
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketPath.java
  src/main/java/com/dapanda/chat/controller/ChatController.java
  src/main/java/com/dapanda/chat/dto/response/CreateChatRoomResponse.java
  src/main/java/com/dapanda/chat/entity/ChatMessage.java
  src/main/java/com/dapanda/chat/entity/ChatParticipant.java
  src/main/java/com/dapanda/chat/entity/ChatRoom.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepository.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/common/config/AllowedOriginPath.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/product/repository/ProductRepository.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/chat/entity/ChatParticipantFixture.java
  src/test/java/com/dapanda/chat/entity/ChatRoomFixture.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
Labels: BE, feat, docs, test

#91 [DP-102] feat: 데이터 상품 자투리 구매 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/MobileDataScrap.java
  src/main/java/com/dapanda/trade/dto/request/TradeMobileDataScrapRequest.java
  src/main/java/com/dapanda/trade/dto/response/TradeMobileDataResponse.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/java/com/dapanda/trade/entity/TradeDetails.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: feat, docs, test

#93 [DP-98] feat: 채팅 메시지 송수신 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketEventListener.java
  src/main/java/com/dapanda/chat/config/WebSocketHandler.java
  src/main/java/com/dapanda/chat/config/WebSocketPath.java
  src/main/java/com/dapanda/chat/controller/WebSocketController.java
  src/main/java/com/dapanda/chat/dto/request/CreateChatMessageRequest.java
  src/main/java/com/dapanda/chat/entity/ChatMessage.java
  src/main/java/com/dapanda/chat/repository/ChatParticipantRepository.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/jwt/JwtPrinciple.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
Labels: BE, feat, docs, test

#92 [DP-80] feat: 상품 등록 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/dto/request/CreateMobileDataRequest.java
  src/main/java/com/dapanda/product/dto/request/CreateProductRequest.java
  src/main/java/com/dapanda/product/dto/request/CreateWifiRequest.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, feat, test

#97 [DP-103] feat: 와이파이 상품 구매 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/request/TradeWifiRequest.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, docs, test

#103 [DP-113] fix: RestDocs 형식 오류 수정
  src/docs/asciidoc/api-docs.adoc
Labels: BE, fix, docs

#99 [DP-111] fix: 데이터 상품 상세 조회 응답에 splitType 반환하도록 수정
  src/main/java/com/dapanda/product/dto/response/MobileDataInfoResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: fix, test

#109 [DP-117] fix: TradeType 필드에 EnumType.STRING 어노테이션 추가
  src/main/java/com/dapanda/trade/entity/Trade.java
Labels: BE, fix

#106 [DP-112] feat: 상품 거래 내역 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/TradeHistorySummary.java
  src/main/java/com/dapanda/trade/dto/request/DefaultPurchaseMobileDataRequest.java
  src/main/java/com/dapanda/trade/dto/request/PurchaseWifiRequest.java
  src/main/java/com/dapanda/trade/dto/request/ScrapPurchaseMobileDataRequest.java
  src/main/java/com/dapanda/trade/dto/response/FindTradeHistoryResponse.java
  src/main/java/com/dapanda/trade/dto/response/TradeProductResponse.java
  src/main/java/com/dapanda/trade/entity/TradeType.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepository.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/repository/TradeRepository.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, docs, test

#104 [DP-107] feat: 참여 중인 채팅방 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketPath.java
  src/main/java/com/dapanda/chat/controller/ChatController.java
  src/main/java/com/dapanda/chat/controller/WebSocketController.java
  src/main/java/com/dapanda/chat/dto/request/ReadJoiningChatRoomRequest.java
  src/main/java/com/dapanda/chat/dto/response/ReadJoiningChatRoomResponse.java
  src/main/java/com/dapanda/chat/entity/ChatRoom.java
  src/main/java/com/dapanda/chat/entity/ChatRoomReadOption.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/chat/entity/ChatMessageFixture.java
  src/test/java/com/dapanda/chat/entity/ChatParticipantFixture.java
  src/test/java/com/dapanda/chat/entity/ChatRoomFixture.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
Labels: BE, feat, docs, test

#115 [DP-123] feat: 내가 받은 리뷰 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/review/controller/ReviewController.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
Labels: BE, docs, test

#120 [DP-126] docs: 채팅방 조회 URL 추가
  src/docs/asciidoc/api-docs.adoc
Labels: BE, docs

#127 [DP-133] fix: 리뷰 조회 쿼리 수정
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/review/dto/response/ReadReceivedReviewResponse.java
  src/main/java/com/dapanda/review/dto/response/ReadWrittenReviewResponse.java
  src/main/java/com/dapanda/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/dapanda/report/controller/ReportControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/entity/ReviewFixture.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
Labels: BE, fix

#138 [DP-142] fix: 상품 상세 조회시 판매자 리뷰 쿼리 수정
  src/main/java/com/dapanda/product/dto/response/MobileDataInfoResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/TestConstants.java
Labels: BE, fix

#130 [DP-130] feat: 나의 상품 판매 정보 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
Labels: BE, feat, docs, test

#139 [DP-137] feat: 요금제 남은 데이터양 조회 기능
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/plan/controller/PlanController.java
  src/main/java/com/dapanda/plan/dto/response/PlanInfoResponse.java
  src/main/java/com/dapanda/plan/repository/PlanRepository.java
  src/main/java/com/dapanda/plan/service/PlanService.java
  src/test/java/com/dapanda/plan/controller/PlanControllerTest.java
  src/test/java/com/dapanda/plan/entity/PlanFixture.java
  src/test/java/com/dapanda/plan/service/PlanServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, test

#140 [DP-132] feat: 구매/판매 데이터양 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/member/controller/MemberController.java
  src/main/java/com/dapanda/member/dto/response/FindDataResponse.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/member/MemberControllerTest.java
  src/test/java/com/dapanda/member/service/MemberServiceTest.java
Labels: BE, feat, docs, test

#142 [DP-145] fix: 캐시 내역 조회 쿼리 수정
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, fix

#146 [DP-146] fix: 와이파이 상품 조회 수정
  src/main/java/com/dapanda/product/dto/WifiSummary.java
  src/main/java/com/dapanda/product/dto/request/CreateWifiRequest.java
  src/main/java/com/dapanda/product/dto/request/UpdateWifiRequest.java
  src/main/java/com/dapanda/product/dto/response/WifiInfoResponse.java
  src/main/java/com/dapanda/product/entity/Wifi.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/WifiFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, fix

#147 [DP-147] refactor: 테스트 코드에 CustomUserDetails 객체 변경
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
Labels: BE, refactor

#151 [DP-150] feat: 상품 판매 정보 조회에 전체 상품 수 추가
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/dto/response/CountCursorPageResponse.java
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, feat, test

#156 [DP-155] fix: 상품 등록 데이터 단위 수정
  src/main/java/com/dapanda/product/dto/request/CreateMobileDataRequest.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, fix, test

#159 [DP-160] fix: 데이터 100MB당 가격 계산 오류 수정
  src/main/java/com/dapanda/product/entity/MobileData.java
Labels: BE, fix

#161 [DP-136] feat: 상품 조회시 판매자 프로필 이미지 및 본인 상품 여부 반환 기능 추가
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/dto/MobileDataSummary.java
  src/main/java/com/dapanda/product/dto/ProductSummary.java
  src/main/java/com/dapanda/product/dto/WifiSummary.java
  src/main/java/com/dapanda/product/dto/response/MobileDataInfoResponse.java
  src/main/java/com/dapanda/product/dto/response/WifiInfoResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/product/entity/WifiFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, docs, test

#149 [DP-115] feat: 이전 채팅 내역 불러오기 기능
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketHandler.java
  src/main/java/com/dapanda/chat/config/WebSocketSecurityConfig.java
  src/main/java/com/dapanda/chat/controller/ChatController.java
  src/main/java/com/dapanda/chat/controller/WebSocketController.java
  src/main/java/com/dapanda/chat/dto/request/CreateChatMessageRequest.java
  src/main/java/com/dapanda/chat/dto/request/ReadChatMessageHistoryRequest.java
  src/main/java/com/dapanda/chat/dto/response/SendChatMessageResponse.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepository.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/jwt/JwtClaim.java
  src/main/java/com/dapanda/jwt/JwtTokenProvider.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/chat/entity/ChatMessageFixture.java
  src/test/java/com/dapanda/chat/entity/ChatParticipantFixture.java
  src/test/java/com/dapanda/chat/entity/ChatRoomFixture.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/product/entity/WifiFixture.java
Labels: BE, feat, docs, test

#165 [DP-163] fix: 데이터 상품 자투리 구매시 가격 업데이트 오류 수정
  src/main/java/com/dapanda/member/dto/response/FindDataResponse.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/plan/dto/response/PlanInfoResponse.java
  src/main/java/com/dapanda/plan/entity/Plan.java
  src/main/java/com/dapanda/plan/service/PlanService.java
  src/main/java/com/dapanda/product/controller/ProductController.java
  src/main/java/com/dapanda/product/dto/MobileDataSummary.java
  src/main/java/com/dapanda/product/dto/ProductSummary.java
  src/main/java/com/dapanda/product/dto/request/CreateMobileDataRequest.java
  src/main/java/com/dapanda/product/dto/request/MobileDataCursorRequest.java
  src/main/java/com/dapanda/product/dto/request/UpdateMobileDataRequest.java
  src/main/java/com/dapanda/product/dto/response/MobileDataInfoResponse.java
  src/main/java/com/dapanda/product/dto/response/ReadSellingProductResponse.java
  src/main/java/com/dapanda/product/entity/MobileData.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/main/java/com/dapanda/trade/controller/TradeController.java
  src/main/java/com/dapanda/trade/dto/MobileDataScrap.java
  src/main/java/com/dapanda/trade/dto/PurchaseHistorySummary.java
  src/main/java/com/dapanda/trade/dto/request/DefaultPurchaseMobileDataRequest.java
  src/main/java/com/dapanda/trade/dto/request/ScrapPurchaseMobileDataRequest.java
  src/main/java/com/dapanda/trade/dto/response/FindMobileDataScrapResponse.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/plan/controller/PlanControllerTest.java
  src/test/java/com/dapanda/plan/entity/PlanFixture.java
  src/test/java/com/dapanda/plan/service/PlanServiceTest.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/MobileDataFixture.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, fix, refactor

#170 [DP-110] feat: 마이페이지 회원 정보 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/member/controller/MemberController.java
  src/main/java/com/dapanda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/member/controller/MemberControllerTest.java
Labels: BE, feat, docs, test

#168 [DP-165] feat: 자신의 메시지 수신 방지를 위한 예외 처리
  src/main/java/com/dapanda/chat/config/MessagePrinciple.java
  src/main/java/com/dapanda/chat/config/OutboundInterceptor.java
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketHandler.java
  src/main/java/com/dapanda/chat/controller/ChatController.java
  src/main/java/com/dapanda/chat/controller/WebSocketController.java
  src/main/java/com/dapanda/chat/dto/SendMessageDto.java
  src/main/java/com/dapanda/chat/dto/response/CreateMessageResponse.java
  src/main/java/com/dapanda/chat/dto/response/ReadChatMessageHistoryResponse.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
Labels: BE, feat

#174 [DP-168] fix: 채팅방 목록 조회 쿼리 수정
  src/main/java/com/dapanda/chat/config/MessagePrinciple.java
  src/main/java/com/dapanda/chat/config/OutboundInterceptor.java
  src/main/java/com/dapanda/chat/controller/WebSocketController.java
  src/main/java/com/dapanda/chat/dto/SendMessageDto.java
  src/main/java/com/dapanda/chat/dto/response/CreateMessageResponse.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
Labels: BE, feat, fix

#177 [DP-131] feat: 캐시 환불 기능
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/config/RedisConfig.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/payment/controller/PaymentController.java
  src/main/java/com/dapanda/payment/dto/request/ChargeCashRequest.java
  src/main/java/com/dapanda/payment/dto/request/RefundCashRequest.java
  src/main/java/com/dapanda/payment/dto/response/ChargeCashResponse.java
  src/main/java/com/dapanda/payment/dto/response/RefundCashResponse.java
  src/main/java/com/dapanda/payment/service/PaymentService.java
  src/main/java/com/dapanda/payment/service/TossPaymentService.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/entity/Trade.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/RedisTestContainerConfig.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/payment/controller/PaymentControllerTest.java
  src/test/java/com/dapanda/payment/service/PaymentServiceTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/resources/application-test.yml
Labels: BE, feat, fix, chore, docs, refactor, test

#184 [DP-182] fix: 헬스체크가 애플리케이션 실행보다 빠른 경우를 대비하여 대기시간 추가
  scripts/start.sh
Labels: BE, fix

#186 [DP-183] fix: 배포 실패 오류 수정
  scripts/start.sh
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: BE, fix

#181 [DP-180] feat: 와이파이 수정 시 이미지 필드 추가
  src/main/java/com/dapanda/product/dto/request/UpdateWifiRequest.java
  src/main/java/com/dapanda/product/repository/ProductImageRepository.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
Labels: BE, feat, test

#187 [DP-181] fix: 데이터 상품 조회 시 정렬 오류 수정
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
Labels: BE, fix, test

#172 [DP-169] fix: 쿠키 세팅에서 도메인 세팅이 누락되어있던 오류 수정
  src/main/java/com/dapanda/auth/controller/AuthController.java
Labels: BE, fix

#193 [DP-187] feat: 채팅방 조회 응답 DTO에 프로필 이미지 URL 필드 추가
  src/main/java/com/dapanda/chat/dto/response/ReadJoiningChatRoomResponse.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryImpl.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
Labels: BE, feat

#189 [DP-185] feat: 매월 1일 이전 등록된 데이터 상품 상태 변경 기능
  src/main/java/com/dapanda/product/repository/ProductCustomRepository.java
  src/main/java/com/dapanda/product/repository/ProductRepository.java
  src/main/java/com/dapanda/product/service/ProductScheduler.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/product/service/ProductServiceTest.java
  src/test/resources/application-test.yml
Labels: BE, feat, test

#191 [DP-186] fix: 와이파이 상품 등록 및 조회 시 시간 검증 로직 수정
  src/main/java/com/dapanda/product/dto/request/CreateWifiRequest.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
Labels: BE, fix, refactor

#209 [DP-194] refactor: 상품 구매 트랜잭션 동시성 처리 로직 개선
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/dapanda/member/repository/MemberRepository.java
  src/main/java/com/dapanda/product/repository/MobileDataRepository.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/repository/ProductRepository.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/trade/controller/TradeConcurrencyTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, feat, fix, refactor, test

#212 [DP-204] fix: 회원 요금제의 총량과 잔량 응답 수정
  src/main/java/com/dapanda/plan/dto/response/PlanInfoResponse.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/test/java/com/dapanda/plan/service/PlanServiceTest.java
Labels: BE, fix

#213 [DP-230] feat: 받은 리뷰 응답 DTO에 title 추가
  src/main/java/com/dapanda/review/dto/response/ReadReceivedReviewResponse.java
  src/main/java/com/dapanda/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
Labels: BE, feat

#215 [DP-188] feat: 채팅 메시지 읽음 상태 Entity 추가
  src/main/java/com/dapanda/chat/entity/ChatMessageReadStatus.java
  src/main/java/com/dapanda/chat/entity/ReadStatus.java
Labels: BE, feat

#219 [DP-207] feat: 채팅방 목록 조회 DTO에 읽지 않은 메시지 카운트 필드 추가
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/chat/controller/ChatController.java
  src/main/java/com/dapanda/chat/dto/request/UpdateReadStatusRequest.java
  src/main/java/com/dapanda/chat/dto/response/ReadJoiningChatRoomResponse.java
  src/main/java/com/dapanda/chat/entity/ChatMessageReadStatus.java
  src/main/java/com/dapanda/chat/entity/ReadStatus.java
  src/main/java/com/dapanda/chat/repository/ChatMessageReadStatusRepository.java
  src/main/java/com/dapanda/chat/repository/ChatMessageRepository.java
  src/main/java/com/dapanda/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/chat/service/ChatServiceTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
Labels: BE, feat, docs, test

#221 [DP-214] fix: 데이터 상품 목록 조회 시 가격 낮은순 정렬 오류 수정
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
Labels: BE, fix

#226 [DP-217] feat: 판매 중인 상품 목록 조회 DTO에 title 필드 추가
  src/main/java/com/dapanda/product/dto/response/ReadSellingProductResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
Labels: BE, feat

#234 [DP-222] docs: 회원 프로필 이미지 변경 API RestDocs에 추가
  .gitignore
  src/docs/asciidoc/api-docs.adoc
  src/test/java/com/dapanda/member/controller/MemberControllerTest.java
Labels: BE, fix, docs

#240 [DP-225] docs: README.md 수정
  README.md
Labels: BE, docs

#241 [DP-218] feat: Prometheus, Grafana 초기 설정
  build.gradle
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: BE, chore

#244 [DP-237] fix: FireBase 앱 초기화 버그 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/com/dapanda/auth/service/CustomOAuth2UserService.java
  src/main/java/com/dapanda/common/config/FirebaseConfig.java
Labels: BE, fix
