Repository URECA-Dapanda/dapanda-backend, pull requests merged in 2025-08, with the labels that each got.

#254 [DP-248] feat: 알림 조회, 삭제 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/fcm_token/controller/FcmTokenController.java
  src/main/java/com/dapanda/fcm_token/dto/request/SaveFcmTokenRequest.java
  src/main/java/com/dapanda/fcm_token/dto/response/NotificationResponse.java
  src/main/java/com/dapanda/fcm_token/entity/NotificationEntity.java
  src/main/java/com/dapanda/fcm_token/repository/NotificationRepository.java
  src/main/java/com/dapanda/fcm_token/service/FcmTokenService.java
  src/test/java/com/dapanda/fcm/controller/FcmTokenControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
Labels: BE, feat, docs, test

#253 [DP-247] fix: 상품 구매/판매 내역 조회 시 상품 대표 이미지 반환하도록 수정
  src/main/java/com/dapanda/product/dto/response/ReadSellingProductResponse.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/dto/PurchaseHistorySummary.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/test/java/com/dapanda/TestConstants.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/product/entity/ProductFixture.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, fix, test

#257 [DP-251] feat: 데이터 상품 판매 가능 양 조회 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/member/controller/MemberController.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/member/controller/MemberControllerTest.java
  src/test/java/com/dapanda/member/service/MemberServiceTest.java
Labels: BE, feat, docs, test

#263 [DP-261] fix: 배포 실패로 인한 RedisConfig 사용하지 않는 Bean 임시 주석
  src/main/java/com/dapanda/common/config/RedisConfig.java
Labels: BE, fix

#265 [DP-262] fix: 데이터 일반 상품 구매 시 거래 데이터양 저장 오류 수정
  src/main/java/com/dapanda/trade/service/TradeService.java
Labels: BE, fix

#271 [DP-268] fix: 리뷰 평점 계산 오류 수정
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/main/java/com/dapanda/trade/repository/TradeDetailsRepository.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, fix

#272 [DP-271] fix: 데이터 상품 자투리 조회 판매자 이미지 URL 추가
  src/main/java/com/dapanda/fcmToken/controller/FcmTokenController.java
  src/main/java/com/dapanda/fcmToken/dto/request/SaveFcmTokenRequest.java
  src/main/java/com/dapanda/fcmToken/dto/response/NotificationResponse.java
  src/main/java/com/dapanda/fcmToken/service/FcmTokenService.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/dto/MobileDataScrap.java
  src/main/java/com/dapanda/trade/dto/PurchaseHistorySummary.java
  src/main/java/com/dapanda/trade/repository/TradeCustomRepositoryImpl.java
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/test/java/com/dapanda/fcm/controller/FcmTokenControllerTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
  src/test/java/com/dapanda/trade/entity/TradeFixture.java
  src/test/java/com/dapanda/trade/service/TradeServiceTest.java
Labels: BE, fix, test

#268 [DP-267] fix: promtail-start.sh 수정
  .github/workflows/cd.yml
  appspec.yml
  docker-compose.yml
  promtail-config.yml
  scripts/install-docker.sh
  scripts/start-promtail.sh
Labels: BE, fix, chore

#247 [DP-238] feat: 오토스케일링 구조를 위한 Redis PubSub 적용
  src/main/java/com/dapanda/common/config/RedisConfig.java
  src/test/java/com/dapanda/chat/controller/ChatControllerTest.java
  src/test/java/com/dapanda/payment/controller/PaymentControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
  src/test/java/com/dapanda/trade/controller/TradeControllerTest.java
Labels: BE, feat

#276 [DP-273] fix: 회원 정보 조회 시 회원 아이디 반환
  src/main/java/com/dapanda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/member/controller/MemberControllerTest.java
Labels: BE, fix

#279 [DP-282] fix: 상품 목록 조회 최신순 정렬 수정
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
Labels: BE, fix

#282 [DP-284] fix: 모니터링 설정 수정
  .github/workflows/cd.yml
  appspec.yml
  docker-compose.yml
  promtail-config.yml
  src/main/resources/logback-spring.xml
Labels: BE, fix

#290 [DP-288] fix: 와이파이 상품 구매 시간 오류 수정
  src/main/java/com/dapanda/trade/service/TradeService.java
  src/main/resources/logback-spring.xml
Labels: BE, fix

#295 [DP-293] fix: start.sh 수정
  scripts/start.sh
Labels: BE, fix

#294 [DP-292] feat: 최초 사용자 역할 변경 기능
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/member/controller/MemberController.java
  src/test/java/com/dapanda/member/controller/MemberControllerTest.java
Labels: BE, feat, docs, test

#304 [DP-303] fix: 상품 데이터양 조회 조건 수정
  src/main/java/com/dapanda/common/aop/LoggingAspect.java
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
Labels: BE, fix

#274 [DP-272] feat: 신고 횟수가 5회 이상인 경우 인증 처리가 안되도록 분기 추가
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
Labels: BE, feat

#299 [DP-294] feat: 셀프 신고 예외 처리 추가
  src/main/java/com/dapanda/chat/repository/ChatMessageRepository.java
  src/main/java/com/dapanda/chat/service/ChatService.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/member/entity/Member.java
  src/main/java/com/dapanda/member/repository/MemberRepositoryCustom.java
  src/main/java/com/dapanda/member/repository/MemberRepositoryImpl.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/main/java/com/dapanda/product/repository/ProductRepository.java
  src/main/java/com/dapanda/product/service/ProductService.java
  src/main/java/com/dapanda/report/entity/ReportTargetCategory.java
  src/main/java/com/dapanda/report/service/ReportService.java
  src/main/java/com/dapanda/review/repository/ReviewRepository.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/test/java/com/dapanda/member/entity/MemberFixture.java
  src/test/java/com/dapanda/report/controller/ReportControllerTest.java
  src/test/java/com/dapanda/report/entity/ReportFixture.java
  src/test/java/com/dapanda/report/service/ReportServiceTest.java
Labels: BE, feat, refactor, test

#305 [DP-301] refactor: Websocket 리팩토링
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/alarm/dto/AlarmMessage.java
  src/main/java/com/dapanda/alarm/event/EventState.java
  src/main/java/com/dapanda/alarm/event/WifiTradeEndEvent.java
  src/main/java/com/dapanda/alarm/event/WifiTradeEvent.java
  src/main/java/com/dapanda/alarm/event/WifiTradeStartEvent.java
  src/main/java/com/dapanda/alarm/handler/WifiTradeEndEventHandler.java
  src/main/java/com/dapanda/alarm/handler/WifiTradeStartEventHandler.java
  src/main/java/com/dapanda/alarm/scheduler/WifiTradeNotificationScheduler.java
  src/main/java/com/dapanda/chat/config/MessagePrinciple.java
  src/main/java/com/dapanda/chat/config/WebSocketEventListener.java
  src/test/java/com/dapanda/alarm/scheduler/WifiTradeNotificationSchedulerTest.java
Labels: BE, refactor

#315 [DP-307] teat: 채팅 테스트 코드 추가
  src/main/java/com/dapanda/alarm/handler/WifiTradeStartEventHandler.java
  src/main/java/com/dapanda/alarm/scheduler/WifiTradeNotificationScheduler.java
  src/main/java/com/dapanda/alarm/service/WifiTradeNotifier.java
  src/main/java/com/dapanda/chat/config/WebSocketConfig.java
  src/main/java/com/dapanda/chat/config/WebSocketPath.java
  src/main/java/com/dapanda/chat/service/RedisPubSubService.java
  src/test/java/com/dapanda/chat/controller/WebSocketControllerTest.java
Labels: BE, test

#314 [DP-312] feat: AuthController 미사용 코드 제거
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/auth/dto/request/LoginRequest.java
  src/main/java/com/dapanda/auth/dto/request/SignupRequest.java
  src/main/java/com/dapanda/auth/dto/response/LoginResponse.java
  src/main/java/com/dapanda/auth/dto/response/SignupResponse.java
  src/main/java/com/dapanda/auth/dto/response/TokenResponse.java
  src/main/java/com/dapanda/auth/info/NaverOAuth2UserInfo.java
  src/main/java/com/dapanda/auth/info/OAuth2UserInfoFactory.java
  src/main/java/com/dapanda/auth/service/AuthService.java
  src/main/java/com/dapanda/auth/service/CustomOAuth2UserService.java
  src/main/java/com/dapanda/auth/service/CustomUserDetailsService.java
  src/main/java/com/dapanda/jwt/JwtTokenProvider.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/auth/service/AuthServiceTest.java
  src/test/java/com/dapanda/member/service/MemberServiceBeanTest.java
Labels: BE, feat, fix, docs, refactor, test

#318 [DP-319] fix: 리뷰 대상자 설정 오류 수정
  src/main/java/com/dapanda/fcmToken/dto/response/NotificationResponse.java
  src/main/java/com/dapanda/fcmToken/entity/NotificationEntity.java
  src/main/java/com/dapanda/fcmToken/repository/NotificationRepository.java
  src/main/java/com/dapanda/fcmToken/service/FcmTokenService.java
  src/main/java/com/dapanda/review/dto/response/ReviewStatsResponse.java
  src/main/java/com/dapanda/review/repository/ReviewRepository.java
  src/main/java/com/dapanda/review/service/ReviewService.java
  src/test/java/com/dapanda/fcm/controller/FcmTokenControllerTest.java
  src/test/java/com/dapanda/review/service/ReviewServiceTest.java
Labels: BE, fix, test

#324 [DP-321] refactor: ResponseEntity 제거
  src/main/java/com/dapanda/member/controller/MemberController.java
Labels: BE, refactor

#332 [DP-332] feat: 와이파이 목록 조회 시 거리 계산 로직 분기 처리
  .github/workflows/cache.yml
  .github/workflows/cd.yml
  src/main/java/com/dapanda/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/dapanda/product/service/ProductService.java
Labels: BE, feat, chore

#333 [DP-331] refactor: SecurityConfig 리팩토링
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/dapanda/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/member/service/MemberService.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
  src/test/java/com/dapanda/product/controller/ProductControllerTest.java
  src/test/java/com/dapanda/review/controller/ReviewControllerTest.java
Labels: BE, feat, refactor

#335 [DP-334] fix: 세션 정책 STATELESS로 수정
  src/main/java/com/dapanda/auth/handler/OAuth2FailureHandler.java
  src/main/java/com/dapanda/common/config/SecurityConfig.java
Labels: BE, fix

#337 [DP-336] fix: 데이터 상품 목록 조회 캐싱 수정
  src/main/java/com/dapanda/product/service/ProductService.java
Labels: BE, fix

#339 [DP-334] fix: 인증인가 트러블 슈팅
  src/main/java/com/dapanda/auth/controller/AuthController.java
  src/main/java/com/dapanda/common/exception/ResultCode.java
  src/main/java/com/dapanda/refreshToken/entity/RefreshToken.java
  src/main/java/com/dapanda/refreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/dapanda/refreshToken/service/RefreshTokenService.java
  src/main/java/com/dapanda/security/config/SecurityConfig.java
  src/main/java/com/dapanda/security/filter/CustomLogoutFilter.java
  src/test/java/com/dapanda/auth/controller/AuthControllerTest.java
Labels: BE, fix

#344 [DP-341] fix: 쿠키 도메인 추가
  src/main/java/com/dapanda/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dapanda/security/filter/CustomLogoutFilter.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: BE, fix

#328 [DP-330] docs: RestDocs 형식 통일
  src/docs/asciidoc/api-docs.adoc
Labels: BE, docs

#345 [DP-333] docs: README.md 최종 수정
  README.md
Labels: BE, docs

#347 [DP-342] fix: 데이터 구매 시 캐시 무효화
  src/main/java/com/dapanda/product/service/ProductService.java
  src/main/java/com/dapanda/trade/service/TradeService.java
Labels: BE, fix
